#!/usr/bin/env bash
# =============================================================================
# tools/validate-templates.sh - Template Validation Script
# =============================================================================
# Part of OmniForge - Infinite Architectures. Instant Foundation.
#
# Validates that template files in example-files/ match their generator functions.
# This ensures documentation (templates) stays in sync with reality (generators).
#
# Usage:
#   ./tools/validate-templates.sh           # Validate all templates
#   ./tools/validate-templates.sh --fix     # Update templates to match generators
#
# Exit codes:
#   0 - All templates valid
#   1 - Validation failed or templates out of sync
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source common library
source "${SCRIPTS_DIR}/lib/common.sh"

# Load configuration
config_load

# =============================================================================
# VALIDATION FUNCTIONS
# =============================================================================

# Main validation orchestrator
validate_all_templates() {
    local errors=0
    local fix_mode="${1:-false}"

    echo "=========================================="
    echo "  Template Validation"
    echo "=========================================="
    echo ""

    if [[ "$fix_mode" == "true" ]]; then
        log_info "Mode: FIX (will update templates)"
    else
        log_info "Mode: VALIDATE (read-only)"
    fi

    echo ""

    # Validate .toolsrc.example
    if ! validate_toolsrc_template "$fix_mode"; then
        ((errors++))
    fi

    echo ""
    echo "=========================================="

    if [[ $errors -eq 0 ]]; then
        log_success "All templates valid"
        return 0
    else
        log_error "Validation failed: $errors template(s) out of sync"
        if [[ "$fix_mode" == "false" ]]; then
            log_info "Run with --fix to update templates"
        fi
        return 1
    fi
}

# Validate .toolsrc.example matches generator
validate_toolsrc_template() {
    local fix_mode="${1:-false}"
    local template="${TEMPLATE_TOOLSRC}"
    local generated="/tmp/.toolsrc.generated.$$"

    log_step "Validating: .toolsrc.example"

    # Check if template exists
    if [[ ! -f "$template" ]]; then
        log_error "Template not found: $template"
        return 1
    fi

    # Generate fresh copy to temp location
    local original_script="${TOOLS_ACTIVATE_SCRIPT}"
    TOOLS_ACTIVATE_SCRIPT="$generated"

    if ! prereqs_local_create_activate_script; then
        log_error "Failed to generate .toolsrc for validation"
        TOOLS_ACTIVATE_SCRIPT="$original_script"
        rm -f "$generated"
        return 1
    fi

    TOOLS_ACTIVATE_SCRIPT="$original_script"

    # Compare content (ignore empty lines and generator comments)
    local template_content generated_content
    template_content=$(grep -v '^$' "$template" | grep -v '^# Generated by:')
    generated_content=$(grep -v '^$' "$generated" | grep -v '^# Generated by:')

    if [[ "$template_content" == "$generated_content" ]]; then
        log_success ".toolsrc.example matches generator"
        rm -f "$generated"
        return 0
    else
        log_error ".toolsrc.example differs from generator"

        if [[ "$fix_mode" == "true" ]]; then
            log_info "Updating template: $template"
            if cp "$generated" "$template"; then
                log_success "Template updated successfully"
                rm -f "$generated"
                return 0
            else
                log_error "Failed to update template"
                rm -f "$generated"
                return 1
            fi
        else
            log_info "Differences found:"
            diff -u "$template" "$generated" || true
            echo ""
            log_info "To fix: ./tools/validate-templates.sh --fix"
            log_info "Or manually: cp ${generated} ${template}"
            return 1
        fi
    fi
}

# =============================================================================
# MAIN EXECUTION
# =============================================================================

main() {
    local fix_mode=false

    # Parse arguments
    for arg in "$@"; do
        case "$arg" in
            --fix)
                fix_mode=true
                ;;
            -h|--help)
                cat << EOF
Usage: $0 [options]

Options:
  --fix       Update templates to match generators
  -h, --help  Show this help message

Examples:
  $0           # Validate all templates (read-only)
  $0 --fix     # Update templates to match generators
EOF
                exit 0
                ;;
            *)
                log_error "Unknown argument: $arg"
                exit 1
                ;;
        esac
    done

    # Run validation
    if validate_all_templates "$fix_mode"; then
        exit 0
    else
        exit 1
    fi
}

main "$@"
